### ISSUE TITLE
Idea for Appendix - Summary list of Gems - 

### ISSUE THREAD

**Issue by fakefarm** [chriskottom/jello-server#1]
Hey Chris, 

Just got the first email. So far, so good! I know we have the `gemfile` but I'm curious if there is place that I could see a list of what gems you choose for API development, and why. Maybe what I'm thinking of is something like an Appendix. 

Any thoughts on that?

Thanks!
Dave

**Comment by chriskottom** [comment]
The list you're thinking of is indeed a part of a sort of appendix - last
email, additional resources and links - but if you look at the final
version of the Gemfile (master branch) it's there.  The biggies are:

   - ActiveModel::Serializers
   - Rack::Cors
   - Rack::Attack
   - Knock (JWT authentication)
   - Doorkeeper (OAuth)
   - Kaminari (pagination)
   - Minitest (testing)

**Comment by fakefarm** [comment]
Great to see. I like knowing what the total area of responsibility is for context. 🔦 

_Thanks again!_
